spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  threads:
    virtual:
      enabled: true
server:
  port: 8080
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 604800000
  amap:
    key: ${AMAP_KEY}
  wechat:
    appid: ${WECHAT_APPID:wx779bb87ab22d48fb}
    secret: ${WECHAT_SECRET}
