package com.roadbook.route.dto;

import lombok.Builder;
import lombok.Data;

import java.util.List;

@Data
@Builder
public class RouteGenerateResponse {

    /** AI-recommended route (primary), shown first with highlight. */
    private RouteDetailResponse primary;

    /** Template-based alternatives for user to choose from. */
    private List<RouteDetailResponse> alternatives;

    /** Total number of options (primary + alternatives). */
    private int totalOptions;

    /** Whether the primary route was generated by AI (true) or template fallback (false). */
    private boolean aiGenerated;
}
